# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlalgorithm',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
