# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0002_auto_20170805_1544'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mlalgorithm',
            new_name='Algorithm',
        ),
    ]
