# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0003_auto_20170805_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='korname',
            field=models.CharField(default='n', max_length=40),
            preserve_default=False,
        ),
    ]
