# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0004_algorithm_korname'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='algorithm_type',
            field=models.CharField(default='supervised', max_length=40),
            preserve_default=False,
        ),
    ]
