# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0005_algorithm_algorithm_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='chartid',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
