# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0006_algorithm_chartid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstpage.Algorithm')),
            ],
        ),
    ]
