# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0007_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='datasetintro',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
